spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
app:
  flyway:
    baseline-on-migrate: true
    baseline-version-clinic: "114"

  datasource:
    clinic:
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 600000
      max-lifetime: 1800000
      minimum-idle: 1
      maximum-pool-size: 5

server:
  port: ${PORT:8080}
  address: 0.0.0.0
  forward-headers-strategy: NATIVE
  tomcat:
    threads:
      max: 25
      min-spare: 5
    max-connections: 150
